"""
AvaxUsdcDegenLp Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import AvaxUsdcDegenLpStrategy
except ImportError:
    from strategy import AvaxUsdcDegenLpStrategy

__all__ = [
    "AvaxUsdcDegenLpStrategy",
]
